### ISSUE TITLE
IE8 error

### ISSUE THREAD

**Issue by jbonigomes** [closingtag/calc-polyfill#12]
I keep on getting this error in IE8:

The value of the property 'contentLoaded' is null or undefined, not a Function object

Is it something I am doing wrong in the set up?

**Comment by closingtag** [comment]
Which file do you reference in your html?

**Comment by jbonigomes** [comment]
calc.js, simply a copy of your polyfill file at:

https://raw.githubusercontent.com/closingtag/calc-polyfill/master/calc.js

my script tag looks like: 

<script src="/assets/js/calc.js"></script>

**Comment by closingtag** [comment]
Please reference the build version:

https://raw.githubusercontent.com/closingtag/calc-polyfill/master/calc.min.js

**Comment by jbonigomes** [comment]
Thanks closingtag, that was a super quick answer, no more errors :)
