### ISSUE TITLE
Doesn't work on Android 4.2.2

### ISSUE THREAD

**Issue by omnibs** [closingtag/calc-polyfill#15]
I've tried to do a simple demo [here](http://julianobs.co/teste-calc.html) and couldn't get it to work on Android 4.2.2:

![](https://sc-cdn.scaleengine.net/i/a5c6b22d972dd336e293f16dd39a2443.png)

I only got it to work on my laptop's Chrome browser using mobile emulation.

**Comment by closingtag** [comment]
There is no support for inline styles yet: https://github.com/closingtag/calc-polyfill#to-do

**Comment by closingtag** [comment]
Support for inline styles is now included.

However as far as I could investigate right now there is no way to get the unparsed contents of a `style`-element in IE8. Therefore this will not work in IE8.

**Comment by omnibs** [comment]
Awesome! Great work @closingtag!

And thanks for letting me know by updating the issue here =]
