### ISSUE TITLE
Simple test case not working on Android 4.0 or 4.2.

### ISSUE THREAD

**Issue by jmheik** [closingtag/calc-polyfill#16]
I'm trying to use this polyfill to get calc grids work with older Android browsers, but without success. This is my simple test case http://codepen.io/anon/pen/RPzKBe . Not sure if it's due bug or unsupported feature or if I'm using the polyfill somehow wrong. Tested on Android 4.0 and 4.2

**Comment by closingtag** [comment]
Would be so kind to test this outside of the context of codepen and report if the issue sill exists.

**Comment by jmheik** [comment]
Sure, I moved the test case here: http://jmheik.github.io/testcases/calc/index.html . Issue still exists on the two phones I tested with.
