### ISSUE TITLE
Rerun after ajax content?

### ISSUE THREAD

**Issue by zerodburn** [closingtag/calc-polyfill#17]
Hi,

I was just wondering if there was a way to get this script to run again after loading in new content that has a CSS width: calc applied to it? E.g. picturefill allows you do to this:

`picturefill({ reevaluate: true });`

At the end of the ajax function, which recalculates the correct images.

By the way, to get the script to work in IE8 for me I had to comment out the console.log messages, as I was getting a console undefined error. Thanks though, it's working well so far.

**Comment by closingtag** [comment]
The method for rerun the polyfill is:

``window.dotheCalc``
