### ISSUE TITLE
Media Queries - Lost grid

### ISSUE THREAD

**Issue by jaydickinson** [closingtag/calc-polyfill#19]
I know media queries don't work but in I8 I was trying out [lost grid] (https://github.com/corysimmons/lost) and got this polyfill working perfectly but If i add a media query with a lost-column/lost grid inside it just breaks the page and shows nothing at all in I8 all the elements disappear.

![screen shot 2015-10-26 at 17 59 06](https://cloud.githubusercontent.com/assets/1121045/10737660/63f684c6-7c0b-11e5-9baf-286458123405.png)

Above Works

Below would break it and show nothing

![screen shot 2015-10-26 at 18 00 37](https://cloud.githubusercontent.com/assets/1121045/10737679/7a0466f2-7c0b-11e5-9702-e8521a322114.png)

Is this expected? or is there a way to just show the original before the media query if i remove the query the content shows as expected is there a workaround? I'd be happy just to lock the grid at a fixed width for I8 and have the polyfill work

Thanks
Jake

**Comment by closingtag** [comment]
Hi,

can you show me the generated CSS and do you use a polyfill for media-queries?

Cheers

**Comment by jaydickinson** [comment]
The CSS that is being generated for that section is below.  I'm using https://github.com/shinnn/lt-ie-9 which has respond bundled in, but with this script removed or added I get the same thing happening whenever I call lost-columns again in the media query.

Thanks 

```
.front-page div {
  width: calc(99.99% * 1/4 - (10px - 10px * 1/4));
  float: left;
  background: red;
  height: 200px; }

.front-page div:nth-child(n) {
  float: left;
  margin-right: 10px;
  clear: none; }

.front-page div:last-child {
  margin-right: 0; }

.front-page div:nth-child(0n) {
  margin-right: 0; }

.front-page div:nth-child(0n + 1) {
  clear: left; }
  .front-page div:nth-child(2n) {
    background: #d51852; }
  .front-page div:nth-child(3n) {
    background: #ee658f; }

  @media screen and (max-width: 600px) {
    .front-page div {
      width: calc(99.99% * 1/2 - (10px - 10px * 1/2));
      margin-bottom: 10px; }
    .front-page div:nth-child(n) {
    float: left;
    margin-right: 10px;
    clear: none; }
    .front-page div:last-child {
    margin-right: 0; }
    .front-page div:nth-child(2n) {
    margin-right: 0; }
    .front-page div:nth-child(2n + 1) {
    clear: left; } 
}
```
