### ISSUE TITLE
Is there a way to trigger this polyfill?

### ISSUE THREAD

**Issue by corysimmons** [closingtag/calc-polyfill#27]
For instance, things like Isotope.js have `relayout()`. Does calc polyfill have anything like that?

I ask because it seems like when I trigger various viewport adjustments (open/close IE8 dev tools, shrink/expand the viewport) it seems to work better and better.

It'd be nice to add a timeout that triggered calc relayout. :D

**Comment by rodebert** [comment]
See #17

**Comment by corysimmons** [comment]
<3 Thanks =)
