### ISSUE TITLE
on IE8 no working

### ISSUE THREAD

**Issue by gongfuxiaocai** [closingtag/calc-polyfill#29]
win.requestAnimationFrame(detectChange) on IE8 is error

**Comment by rodebert** [comment]
Did you include the correct file https://github.com/closingtag/calc-polyfill/blob/master/dist/calc.min.js ?

**Comment by gongfuxiaocai** [comment]
I require ../dist/cacl.js

**Comment by gongfuxiaocai** [comment]
yes, but I import "../dist/calc.js"

**Comment by rodebert** [comment]
There is a polyfill included in this file. Did you generated that file via grunt?

**Comment by gongfuxiaocai** [comment]
I generated my files by gulp

**Comment by rodebert** [comment]
How do you include this polyfill in your project? bower or download the file?

**Comment by rodebert** [comment]
I close this because of no further response.
