### ISSUE TITLE
Invalid procedure call or argument

### ISSUE THREAD

**Issue by ryangiglio** [closingtag/calc-polyfill#3]
(I got the access denied figured out)

I'm getting an error "Invalid procedure call or argument" on line 252 char 7 (http://d.pr/i/lIc2). That's the line with querySelectorAll() on it, which I know you specify as a dependency in the Docs, but I have IE8 running in Standards Mode which is supposed to support the function and I'm still getting this error.

You can see this at http://railex.thesmackpack.com in IE8

**Comment by closingtag** [comment]
Support for media-queries is now integrated. So no support for respond.js. You have to polyfill window.matchMedia.
