### ISSUE TITLE
Dont work with @font-face or ::moz-

### ISSUE THREAD

**Issue by kivervinicius** [closingtag/calc-polyfill#5]
The polyfill dont work on my css, i use @font-face in my code and any moz- and webkit.

**Comment by mrdevin** [comment]
:+1: 
I am also having the same issue. ``` @charset 'UTF-8'``` also causes the script to break

**Comment by olivier-g** [comment]
Same here with `@webkit` for css keyframe animations :disappointed:

**Comment by closingtag** [comment]
This is fixed now. Keyframes, charset, font-face and imports are now silently ignored.

Also -moz-calc should work now although the last Firefox version using this prefix was Firefox 15

**Comment by olivier-g** [comment]
@closingtag :+1: Amazing thank you for this!
