### ISSUE TITLE
Support respond.js

### ISSUE THREAD

**Issue by corysimmons** [closingtag/calc-polyfill#7]
Please?

**Comment by closingtag** [comment]
Support for media-queries is now integrated. So no support for respond.js. You have to polyfill window.matchMedia.

**Comment by corysimmons** [comment]
Sorry to keep bugging you, but I'm working on a [combo polyfill](https://github.com/corysimmons/ie-love) (kinda like lt-ie-9 + calc-polyfill) and ran into this issue again.

I tried putting matchMedia polyfill above calc-polyfill instead of using respond.js, but didn't have any luck.

Could you explain how this works exactly? I can PR the README once I understand it.

**Comment by rodebert** [comment]
@corysimmons I will update the testcase a soon as possible.

**Comment by corysimmons** [comment]
@closingtag Thanks! :+1:
