### ISSUE TITLE
Support for multiplication and division with percentages

### ISSUE THREAD

**Issue by corysimmons** [closingtag/calc-polyfill#8]
`width: calc(50px * 2)` works fine, `width: calc(50% * 2)` results in `240100`, `width: calc(50% / 2)` results in `1`.

**Comment by closingtag** [comment]
This is fixed.

Although I do not know what you are trying to accomplish with ´´width: calc(50% / 2)´´. Why not writing ´´width: 25%´´. I think that is not what ´´calc()´´ is supposed to used for.

**Comment by corysimmons** [comment]
Thanks. I'm not doing `width: calc(50% / 2)`. The math is much more complicated than that. Just wanted to show a basic example.
